# -*- coding: utf-8 -*-
"""data analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nxyX0j3iuvk9IdvX2uwRPj2AEgLHyzO2
"""

from numpy.random import seed
from scipy.stats import spearmanr
from numpy import std
from numpy import mean
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns # for data visualization
from xlrd import open_workbook
import xlrd

wb = xlrd.open_workbook("Data1.xlsx")
sheet = wb.sheet_by_index(0)

# GDP Growth vs inflation no lag
data1 = [sheet.cell_value(r, c) for c in range(4, 5) for r in range(4, 28)]
data2 = [sheet.cell_value(r, c) for c in range(2, 3) for r in range(4, 28)]
print(data1)
print(data2)
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))
pyplot.plot(data1,data2,'o', color='purple')
z = np.polyfit(data1, data2, 1)
p = np.poly1d(z)
pyplot.plot(data1,p(data1),"r--", color='pink')
plt.title('Correlation')
plt.xlabel('Inflation no lag')
plt.ylabel('GDP Growth')
pyplot.savefig('lag0.jpg')
pyplot.show()
# corr, _ = spearmanr(data1, data2)
corr = np.corrcoef(data1, data2)
print(corr[0,1])

# GDP Growth vs inflation first lag
data1 = [sheet.cell_value(r, c) for c in range(4, 5) for r in range(3, 27)]
data2 = [sheet.cell_value(r, c) for c in range(2, 3) for r in range(4, 28)]
print(data1)
print(data2)
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))
pyplot.plot(data1,data2,'o', color='purple')
z = np.polyfit(data1, data2, 1)
p = np.poly1d(z)
pyplot.plot(data1,p(data1),"r--", color='pink')
plt.title('Correlation')
plt.xlabel('Inflation first lag')
plt.ylabel('GDP Growth')
pyplot.savefig('lag1.jpg')
pyplot.show()
# corr, _ = spearmanr(data1, data2)
corr = np.corrcoef(data1, data2)
print(corr[0,1])

# GDP Growth vs inflation second lag
data1 = [sheet.cell_value(r, c) for c in range(4, 5) for r in range(2, 26)]
data2 = [sheet.cell_value(r, c) for c in range(2, 3) for r in range(4, 28)]
print(data1)
print(data2)
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))
pyplot.plot(data1,data2,'o', color='purple')
z = np.polyfit(data1, data2, 1)
p = np.poly1d(z)
pyplot.plot(data1,p(data1),"r--", color='pink')
plt.title('Correlation')
plt.xlabel('Inflation second lag')
plt.ylabel('GDP Growth')
pyplot.savefig('lag2.jpg')
pyplot.show()
# corr, _ = spearmanr(data1, data2)
corr = np.corrcoef(data1, data2)
print(corr[0,1])

# GDP Growth vs inflation third lag
data1 = [sheet.cell_value(r, c) for c in range(4, 5) for r in range(1, 25)]
data2 = [sheet.cell_value(r, c) for c in range(2, 3) for r in range(4, 28)]
print(data1)
print(data2)
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))
pyplot.plot(data1,data2,'o', color='purple')
z = np.polyfit(data1, data2, 1)
p = np.poly1d(z)
pyplot.plot(data1,p(data1),"r--", color='pink')
plt.title('Correlation')
plt.xlabel('Inflation third lag')
plt.ylabel('GDP Growth')
pyplot.savefig('lag3.jpg')
# corr, _ = spearmanr(data1, data2)
corr = np.corrcoef(data1, data2)
print(corr[0,1])

# Liquidity Rate vs inflation no lag
data1 = [sheet.cell_value(r, c) for c in range(4, 5) for r in range(4, 28)]
data2 = [sheet.cell_value(r, c) for c in range(6, 7) for r in range(4, 28)]
print(data1)
print(data2)
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))
pyplot.plot(data1,data2,'o', color='purple')
z = np.polyfit(data1, data2, 1)
p = np.poly1d(z)
pyplot.plot(data1,p(data1),"r--", color='pink')
plt.title('Correlation')
plt.xlabel('Inflation no lag')
plt.ylabel('Liquidity Rate')
pyplot.savefig('lag0.jpg')
pyplot.show()
# corr, _ = spearmanr(data1, data2)
corr = np.corrcoef(data1, data2)
print(corr[0,1])

# Liquidity Rate vs inflation first lag
data1 = [sheet.cell_value(r, c) for c in range(4, 5) for r in range(3, 27)]
data2 = [sheet.cell_value(r, c) for c in range(2, 3) for r in range(4, 28)]
print(data1)
print(data2)
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))
pyplot.plot(data1,data2,'o', color='purple')
z = np.polyfit(data1, data2, 1)
p = np.poly1d(z)
pyplot.plot(data1,p(data1),"r--", color='pink')
plt.title('Correlation')
plt.xlabel('Inflation first lag')
plt.ylabel('Liquidity Rate')
pyplot.savefig('lag1.jpg')
pyplot.show()
# corr, _ = spearmanr(data1, data2)
corr = np.corrcoef(data1, data2)
print(corr[0,1])

# Liquidity Rate vs inflation second lag
data1 = [sheet.cell_value(r, c) for c in range(4, 5) for r in range(2, 26)]
data2 = [sheet.cell_value(r, c) for c in range(2, 3) for r in range(4, 28)]
print(data1)
print(data2)
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))
pyplot.plot(data1,data2,'o', color='purple')
z = np.polyfit(data1, data2, 1)
p = np.poly1d(z)
pyplot.plot(data1,p(data1),"r--", color='pink')
plt.title('Correlation')
plt.xlabel('Inflation second lag')
plt.ylabel('Liquidity Rate Growth')
pyplot.savefig('lag2.jpg')
pyplot.show()
# corr, _ = spearmanr(data1, data2)
corr = np.corrcoef(data1, data2)
print(corr[0,1])

# Liquidity Rate vs inflation third lag
data1 = [sheet.cell_value(r, c) for c in range(4, 5) for r in range(1, 25)]
data2 = [sheet.cell_value(r, c) for c in range(2, 3) for r in range(4, 28)]
print(data1)
print(data2)
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))
pyplot.plot(data1,data2,'o', color='purple')
z = np.polyfit(data1, data2, 1)
p = np.poly1d(z)
pyplot.plot(data1,p(data1),"r--", color='pink')
plt.title('Correlation')
plt.xlabel('Inflation third lag')
plt.ylabel('Liquidity Rate')
pyplot.savefig('lag3.jpg')
# corr, _ = spearmanr(data1, data2)
corr = np.corrcoef(data1, data2)
print(corr[0,1])

# Inflation vs GDP Growth no lag
data1 = [sheet.cell_value(r, c) for c in range(2, 3) for r in range(4, 28)]
data2 = [sheet.cell_value(r, c) for c in range(4, 5) for r in range(4, 28)]
print(data1)
print(data2)
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))
pyplot.plot(data1,data2,'o', color='aqua')
z = np.polyfit(data1, data2, 1)
p = np.poly1d(z)
pyplot.plot(data1,p(data1),"r--", color='navy')
plt.title('Correlation')
plt.xlabel('GDP Growth no lag')
plt.ylabel('Inflation')
pyplot.savefig('lag0.jpg')
pyplot.show()
# corr, _ = spearmanr(data1, data2)
corr = np.corrcoef(data1, data2)
print(corr[0,1])

# Inflation vs GDP Growth first lag
data1 = [sheet.cell_value(r, c) for c in range(2, 3) for r in range(3, 27)]
data2 = [sheet.cell_value(r, c) for c in range(4, 5) for r in range(4, 28)]
print(data1)
print(data2)
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))
pyplot.plot(data1,data2,'o', color='aqua')
z = np.polyfit(data1, data2, 1)
p = np.poly1d(z)
pyplot.plot(data1,p(data1),"r--", color='navy')
plt.title('Correlation')
plt.xlabel('GDP Growth first lag')
plt.ylabel('Inflation')
pyplot.savefig('lag1.jpg')
pyplot.show()
# corr, _ = spearmanr(data1, data2)
corr = np.corrcoef(data1, data2)
print(corr[0,1])

# Inflation vs GDP Growth second lag
data1 = [sheet.cell_value(r, c) for c in range(2, 3) for r in range(2, 26)]
data2 = [sheet.cell_value(r, c) for c in range(4, 5) for r in range(4, 28)]
print(data1)
print(data2)
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))
pyplot.plot(data1,data2,'o', color='aqua')
z = np.polyfit(data1, data2, 1)
p = np.poly1d(z)
pyplot.plot(data1,p(data1),"r--", color='navy')
plt.title('Correlation')
plt.xlabel('GDP Growth second lag')
plt.ylabel('Inflation')
pyplot.savefig('lag2.jpg')
pyplot.show()
# corr, _ = spearmanr(data1, data2)
corr = np.corrcoef(data1, data2)
print(corr[0,1])

# Inflation vs GDP Growth third lag
data1 = [sheet.cell_value(r, c) for c in range(2, 3) for r in range(1, 25)]
data2 = [sheet.cell_value(r, c) for c in range(4, 5) for r in range(4, 28)]
print(data1)
print(data2)
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))
pyplot.plot(data1,data2,'o', color='aqua')
z = np.polyfit(data1, data2, 1)
p = np.poly1d(z)
pyplot.plot(data1,p(data1),"r--", color='navy')
plt.title('Correlation')
plt.xlabel('GDP Growth third lag')
plt.ylabel('Inflation')
pyplot.savefig('lag3.jpg')
# corr, _ = spearmanr(data1, data2)
corr = np.corrcoef(data1, data2)
print(corr[0,1])

# Liquidity Rate vs GDP Growth no lag
data1 = [sheet.cell_value(r, c) for c in range(2, 3) for r in range(4, 28)]
data2 = [sheet.cell_value(r, c) for c in range(6, 7) for r in range(4, 28)]
print(data1)
print(data2)
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))
pyplot.plot(data1,data2,'o', color='aqua')
z = np.polyfit(data1, data2, 1)
p = np.poly1d(z)
pyplot.plot(data1,p(data1),"r--", color='navy')
plt.title('Correlation')
plt.xlabel('GDP Growth no lag')
plt.ylabel('Liquidity Rate')
pyplot.savefig('lag0.jpg')
pyplot.show()
# corr, _ = spearmanr(data1, data2)
corr = np.corrcoef(data1, data2)
print(corr[0,1])

# Liquidity Rate vs GDP Growth first lag
data1 = [sheet.cell_value(r, c) for c in range(2, 3) for r in range(3, 27)]
data2 = [sheet.cell_value(r, c) for c in range(6, 7) for r in range(4, 28)]
print(data1)
print(data2)
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))
pyplot.plot(data1,data2,'o', color='aqua')
z = np.polyfit(data1, data2, 1)
p = np.poly1d(z)
pyplot.plot(data1,p(data1),"r--", color='navy')
plt.title('Correlation')
plt.xlabel('GDP Growth first lag')
plt.ylabel('Liquidity Rate')
pyplot.savefig('lag1.jpg')
pyplot.show()
# corr, _ = spearmanr(data1, data2)
corr = np.corrcoef(data1, data2)
print(corr[0,1])

# Liquidity Rate vs GDP Growth second lag
data1 = [sheet.cell_value(r, c) for c in range(2, 3) for r in range(2, 26)]
data2 = [sheet.cell_value(r, c) for c in range(6, 7) for r in range(4, 28)]
print(data1)
print(data2)
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))
pyplot.plot(data1,data2,'o', color='aqua')
z = np.polyfit(data1, data2, 1)
p = np.poly1d(z)
pyplot.plot(data1,p(data1),"r--", color='navy')
plt.title('Correlation')
plt.xlabel('GDP Growth second lag')
plt.ylabel('Liquidity Rate')
pyplot.savefig('lag2.jpg')
pyplot.show()
# corr, _ = spearmanr(data1, data2)
corr = np.corrcoef(data1, data2)
print(corr[0,1])

# Liquidity Rate vs GDP Growth third lag
data1 = [sheet.cell_value(r, c) for c in range(2, 3) for r in range(1, 25)]
data2 = [sheet.cell_value(r, c) for c in range(6, 7) for r in range(4, 28)]
print(data1)
print(data2)
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))
pyplot.plot(data1,data2,'o', color='aqua')
z = np.polyfit(data1, data2, 1)
p = np.poly1d(z)
pyplot.plot(data1,p(data1),"r--", color='navy')
plt.title('Correlation')
plt.xlabel('GDP Growth third lag')
plt.ylabel('Liquidity Rate')
pyplot.savefig('lag3.jpg')
# corr, _ = spearmanr(data1, data2)
corr = np.corrcoef(data1, data2)
print(corr[0,1])

# Inflation vs Liquidity Rate no lag
data1 = [sheet.cell_value(r, c) for c in range(6, 7) for r in range(4, 28)]
data2 = [sheet.cell_value(r, c) for c in range(4, 5) for r in range(4, 28)]
print(data1)
print(data2)
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))
pyplot.plot(data1,data2,'o', color='YellowGreen')
z = np.polyfit(data1, data2, 1)
p = np.poly1d(z)
pyplot.plot(data1,p(data1),"r--", color='SpringGreen')
plt.title('Correlation')
plt.xlabel('Liquidity Rate no lag')
plt.ylabel('Inflation')
pyplot.savefig('lag0.jpg')
pyplot.show()
# corr, _ = spearmanr(data1, data2)
corr = np.corrcoef(data1, data2)
print(corr[0,1])

# Inflation vs Liquidity Rate first lag
data1 = [sheet.cell_value(r, c) for c in range(6, 7) for r in range(3, 27)]
data2 = [sheet.cell_value(r, c) for c in range(4, 5) for r in range(4, 28)]
print(data1)
print(data2)
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))
pyplot.plot(data1,data2,'o', color='YellowGreen')
z = np.polyfit(data1, data2, 1)
p = np.poly1d(z)
pyplot.plot(data1,p(data1),"r--", color='SpringGreen')
plt.title('Correlation')
plt.xlabel('Liquidity Rate first lag')
plt.ylabel('Inflation')
pyplot.savefig('lag1.jpg')
pyplot.show()
# corr, _ = spearmanr(data1, data2)
corr = np.corrcoef(data1, data2)
print(corr[0,1])

# Inflation vs Liquidity Rate second lag
data1 = [sheet.cell_value(r, c) for c in range(6, 7) for r in range(2, 26)]
data2 = [sheet.cell_value(r, c) for c in range(4, 5) for r in range(4, 28)]
print(data1)
print(data2)
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))
pyplot.plot(data1,data2,'o', color='YellowGreen')
z = np.polyfit(data1, data2, 1)
p = np.poly1d(z)
pyplot.plot(data1,p(data1),"r--", color='SpringGreen')
plt.title('Correlation')
plt.xlabel('Liquidity Rate second lag')
plt.ylabel('Inflation')
pyplot.savefig('lag2.jpg')
pyplot.show()
# corr, _ = spearmanr(data1, data2)
corr = np.corrcoef(data1, data2)
print(corr[0,1])

# Inflation vs Liquidity Rate third lag
data1 = [sheet.cell_value(r, c) for c in range(6, 7) for r in range(1, 25)]
data2 = [sheet.cell_value(r, c) for c in range(4, 5) for r in range(4, 28)]
print(data1)
print(data2)
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))
pyplot.plot(data1,data2,'o', color='YellowGreen')
z = np.polyfit(data1, data2, 1)
p = np.poly1d(z)
pyplot.plot(data1,p(data1),"r--", color='SpringGreen')
plt.title('Correlation')
plt.xlabel('Liquidity Rate third lag')
plt.ylabel('Inflation')
pyplot.savefig('lag3.jpg')
# corr, _ = spearmanr(data1, data2)
corr = np.corrcoef(data1, data2)
print(corr[0,1])

# GDP Growth vs Liquidity Rate no lag
data1 = [sheet.cell_value(r, c) for c in range(6, 7) for r in range(4, 28)]
data2 = [sheet.cell_value(r, c) for c in range(2, 3) for r in range(4, 28)]
print(data1)
print(data2)
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))
pyplot.plot(data1,data2,'o', color='YellowGreen')
z = np.polyfit(data1, data2, 1)
p = np.poly1d(z)
pyplot.plot(data1,p(data1),"r--", color='SpringGreen')
plt.title('Correlation')
plt.xlabel('Liquidity Rate no lag')
plt.ylabel('GDP Growth')
pyplot.savefig('lag0.jpg')
pyplot.show()
# corr, _ = spearmanr(data1, data2)
corr = np.corrcoef(data1, data2)
print(corr[0,1])

# GDP Growth vs Liquidity Rate first lag
data1 = [sheet.cell_value(r, c) for c in range(6, 7) for r in range(3, 27)]
data2 = [sheet.cell_value(r, c) for c in range(2, 3) for r in range(4, 28)]
print(data1)
print(data2)
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))
pyplot.plot(data1,data2,'o', color='YellowGreen')
z = np.polyfit(data1, data2, 1)
p = np.poly1d(z)
pyplot.plot(data1,p(data1),"r--", color='SpringGreen')
plt.title('Correlation')
plt.xlabel('Liquidity Rate first lag')
plt.ylabel('GDP Growth')
pyplot.savefig('lag1.jpg')
pyplot.show()
# corr, _ = spearmanr(data1, data2)
corr = np.corrcoef(data1, data2)
print(corr[0,1])

# GDP Growth vs Liquidity Rate second lag
data1 = [sheet.cell_value(r, c) for c in range(6, 7) for r in range(2, 26)]
data2 = [sheet.cell_value(r, c) for c in range(2, 3) for r in range(4, 28)]
print(data1)
print(data2)
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))
pyplot.plot(data1,data2,'o', color='YellowGreen')
z = np.polyfit(data1, data2, 1)
p = np.poly1d(z)
pyplot.plot(data1,p(data1),"r--", color='SpringGreen')
plt.title('Correlation')
plt.xlabel('Liquidity Rate second lag')
plt.ylabel('GDP Growth')
pyplot.savefig('lag2.jpg')
pyplot.show()
# corr, _ = spearmanr(data1, data2)
corr = np.corrcoef(data1, data2)
print(corr[0,1])

# GDP Growth vs Liquidity Rate third lag
data1 = [sheet.cell_value(r, c) for c in range(6, 7) for r in range(1, 25)]
data2 = [sheet.cell_value(r, c) for c in range(2, 3) for r in range(4, 28)]
print(data1)
print(data2)
print('data1: mean=%.3f stdv=%.3f' % (mean(data1), std(data1)))
print('data2: mean=%.3f stdv=%.3f' % (mean(data2), std(data2)))
pyplot.plot(data1,data2,'o', color='YellowGreen')
z = np.polyfit(data1, data2, 1)
p = np.poly1d(z)
pyplot.plot(data1,p(data1),"r--", color='SpringGreen')
plt.title('Correlation')
plt.xlabel('Liquidity Rate third lag')
plt.ylabel('GDP Growth')
pyplot.savefig('lag3.jpg')
# corr, _ = spearmanr(data1, data2)
corr = np.corrcoef(data1, data2)
print(corr[0,1])

heatMap = pd.read_csv("Data2.csv")
heatMap.head()

heatMap  = heatMap.set_index('inflation')
heatMap

plt.figure(figsize=(8,6))
sns.heatmap(heatMap)
plt.savefig('heat1.jpg')

heatMap = pd.read_csv("Data3.csv")
heatMap.head()

heatMap  = heatMap.set_index('GDP Growth')
heatMap

plt.figure(figsize=(8,6))
sns.heatmap(heatMap)
plt.savefig('heat2.jpg')

heatMap = pd.read_csv("Data4.csv")
heatMap.head()

heatMap  = heatMap.set_index('Liquidity Rate')
heatMap

plt.figure(figsize=(8,6))
sns.heatmap(heatMap)
plt.savefig('heat3.jpg')